@startuml bibliotheque
left to right direction
skinparam actorStyle awesome

actor Membre
actor Bibliothécaire
actor "Système de notification" as SysNotif

rectangle "Système de bibliothèque" {

    usecase "Rechercher un livre"      as UC1
    usecase "Emprunter un livre"       as UC2
    usecase "Retourner un livre"       as UC3
    usecase "Consulter son historique" as UC4
    usecase "Prolonger un emprunt"     as UC5
    usecase "Vérifier disponibilité"   as UC6

    usecase "Ajouter un livre"         as UC7
    usecase "Retirer un livre"         as UC8
    usecase "Gérer les retards"        as UC9
    usecase "Envoyer une notification" as UC10

    Membre       --> UC1
    Membre       --> UC2
    Membre       --> UC3
    Membre       --> UC4
    Membre       --> UC5

    Bibliothécaire --> UC7
    Bibliothécaire --> UC8
    Bibliothécaire --> UC9

    SysNotif --> UC10

    UC2  ..> UC6  : <<include>>
    UC9  ..> UC10 : <<include>>
    UC5  ..> UC2  : <<extend>>
}
@enduml
